title: Hi I'm Erin
description: Things too long or boring for Twitter
author: eritbh
footer_links:
- name: Mail
  url: mailto:hello@eritbh.me
- name: GitHub
  url: https://github.com/eritbh
- name: Twitter
  url: https://twitter.com/eritbh
- name: Donate
  url: https://ko-fi.com/eritbh

permalink: pretty
plugins:
- jekyll-feed
defaults:
- scope: 
    type: posts
  values: 
    layout: default
- scope:
    type: pages
  values:
    layout: default
