title: Hi I'm Erin
description: Things too long or boring for Twitter
author: eritbh

footer_links:
- name: Mastodon
  url: https://tech.lgbt/@eritbh
  rel: me
- name: Twitter
  url: https://twitter.com/eritbh
  rel: me
- name: GitHub
  url: https://github.com/eritbh
  rel: me
- name: Donate
  url: https://ko-fi.com/eritbh
  rel: me

lang: en-US
text_direction: ltr
permalink: pretty
date_format: "%-d %B %Y"
plugins:
- jekyll-feed
- jekyll-github-metadata

collections:
  photos:
    output: true
    permalink: /:collection/:path/

defaults:
- scope:
    type: posts
  values:
    layout: default
- scope:
    type: pages
  values:
    layout: default
- scope:
    type: photos
  values:
    layout: photo
    title: ""

include:
- .well-known
